# Generated by Django 3.2.2 on 2021-05-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rewards',
            field=models.ManyToManyField(blank=True, related_name='user_rewards', to='users.Reward'),
        ),
    ]
