# Generated by Django 3.2.2 on 2021-05-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_rewards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorsexerciseresult',
            name='is_thebest',
        ),
        migrations.AddField(
            model_name='indicatorsexercise',
            name='best_result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99999),
        ),
        migrations.AlterField(
            model_name='indicatorsexercise',
            name='vector',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Без вектора'), (2, 'Вектор')], default=1),
        ),
    ]
