# Generated by Django 3.2.2 on 2021-05-18 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210518_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorsexerciseresult',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.indicatorsblock'),
        ),
    ]
