# Generated by Django 3.2.2 on 2021-05-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_indicatorsexerciseresult_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorsexerciseresult',
            name='block',
        ),
        migrations.AddField(
            model_name='indicatorsexercise',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_exercise', to='users.indicatorsblock'),
        ),
        migrations.AddField(
            model_name='indicatorsexerciseresult',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_exercise_result', to='users.indicatorsexercise'),
        ),
    ]
