# Generated by Django 3.2.2 on 2021-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210518_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='c_pass',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
