# Generated by Django 3.2.2 on 2021-05-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_indicators_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorsMainStatics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=2, default=0, max_digits=99999)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_main_statics', to='users.indicatorsblock')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorsExStatics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=2, default=0, max_digits=99999)),
                ('main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_ex_statics', to='users.indicatorsmainstatics')),
            ],
        ),
    ]
