# Generated by Django 3.2.2 on 2021-05-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_indicatorsexstatics_indicatorsmainstatics'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorsexstatics',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_ex_statics_e', to='users.indicatorsexercise'),
        ),
        migrations.AddField(
            model_name='user',
            name='ex_statics',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_ex_statics', to='users.IndicatorsExStatics'),
        ),
        migrations.AddField(
            model_name='user',
            name='main_statics',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_main_statics', to='users.IndicatorsMainStatics'),
        ),
    ]
