# Generated by Django 3.2.2 on 2021-06-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210523_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player_number',
            field=models.CharField(default='01', max_length=3),
        ),
    ]
