# Generated by Django 3.2.2 on 2021-05-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lessonblock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lessonsblock'),
        ),
        migrations.AddField(
            model_name='lessonsblock',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
