# Generated by Django 3.2.2 on 2021-05-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210517_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessonblock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.lessonsblock'),
        ),
    ]
