# Generated by Django 3.2.2 on 2021-05-17 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lesson_lessonblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='donehomework',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='homework',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
