# Generated by Django 3.2.2 on 2021-05-19 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210519_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donehomework',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_homework', to='core.homework'),
        ),
    ]
