# Generated by Django 3.2.2 on 2021-06-07 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_team_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBlockRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lessonsblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
