# Generated by Django 3.2.2 on 2021-06-09 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_donehomework_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsblock',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
