from django.urls import path

from . import views

urlpatterns = [
    path('', views.auth.signin, name='signin'),
    path('signout/', views.auth.signout, name='signout'),

    path('player/main/', views.player.main, name='player_main'),
    path('player/cabinet/', views.player.cabinet, name='player_cabinet'),
    path('player/p/<int:pk>/', views.player.p, name='player_p'),
    path('player/team/', views.player.team, name='player_team'),
    path('player/homeworks/', views.player.homeworks, name='player_homeworks'),
    path('player/homeworks/<int:pk>/', views.player.homework, name='player_homework'),
    path('player/my_way/', views.player.my_way, name='player_my_way'),
    path('player/my_way/<int:pk>/', views.player.way, name='player_way'),

    path('coach/main/', views.coach.main, name='coach_main'),
    path('coach/users/', views.coach.users, name='coach_users'),
    path('coach/trainers/', views.coach.trainers, name='coach_trainers'),
    path('coach/trainers/create/', views.coach.trainers_create, name='coach_trainers_create'),
    path('coach/trainers/<int:pk>/edit/', views.coach.trainers_edit, name='coach_trainers_edit'),
    path('coach/indicators/', views.coach.indicators, name='coach_indicators'),
    path('coach/indicators/<int:pk>/create/', views.coach.indicators_create, name='coach_indicators_create'),
    path('coach/indicators/delete/<int:pk>/', views.coach.indicators_delete, name='coach_indicators_delete'),
    path('coach/indicators/<int:pk>/edit/<int:epk>/', views.coach.indicators_edit, name='coach_indicators_edit'),
    path('coach/rewards/', views.coach.rewards, name='coach_rewards'),
    path('coach/rewards/create/', views.coach.rewards_create, name='coach_rewards_create'),
    path('coach/rewards/edit/<int:pk>/', views.coach.rewards_edit, name='coach_rewards_edit'),
    path('coach/rewards/delete/<int:pk>/', views.coach.rewards_delete, name='coach_rewards_delete'),
    path('coach/team/<int:pk>/main/', views.coach.team, name='coach_team'),
    path('coach/team/<int:pk>/delete/', views.coach.team_delete, name='coach_team_delete'),
    path('coach/team/create/', views.coach.team_create, name='coach_team_create'),
    path('coach/team/<int:pk>/users/create/', views.coach.team_users_create, name='coach_team_users_create'),
    path('coach/team/<int:pk>/users/<int:upk>/edit/', views.coach.team_users_edit, name='coach_team_users_edit'),
    path('coach/team/<int:pk>/users/<int:upk>/delete/', views.coach.team_users_delete, name='coach_team_users_delete'),
    path('coach/team/<int:pk>/lessons_blocks/', views.coach.team_lessons_blocks, name='coach_team_lessons_blocks'),
    path('coach/team/<int:pk>/lessons_blocks/create/', views.coach.team_lessons_blocks_create, name='coach_team_lessons_blocks_create'),
    path('coach/team/<int:pk>/lessons_blocks/<int:bpk>/edit/', views.coach.team_lessons_blocks_edit, name='coach_team_lessons_blocks_edit'),
    path('coach/team/<int:pk>/lessons_blocks/<int:bpk>/delete/', views.coach.team_lessons_blocks_delete, name='coach_team_lessons_blocks_delete'),
    path('coach/team/<int:pk>/lessons_blocks/<int:bpk>/lessons/', views.coach.team_lessons_blocks_lessons, name='coach_team_lessons_blocks_lessons'),
    path('coach/team/<int:pk>/lessons_blocks/<int:bpk>/lessons/create/', views.coach.team_lessons_blocks_lessons_create, name='coach_team_lessons_blocks_lessons_create'),
    path('coach/team/<int:pk>/lessons_blocks/<int:bpk>/lessons/<int:lpk>/edit/', views.coach.team_lessons_blocks_lessons_edit, name='coach_team_lessons_blocks_lessons_edit'),
    path('coach/team/<int:pk>/lessons_blocks/<int:bpk>/lessons/<int:lpk>/visit/', views.coach.team_lessons_blocks_lessons_visit, name='coach_team_lessons_blocks_lessons_visit'),
    path('coach/team/<int:pk>/lessons_blocks/<int:bpk>/lessons/<int:lpk>/delete/', views.coach.team_lessons_blocks_lessons_delete, name='coach_team_lessons_blocks_lessons_delete'),
    path('coach/team/<int:pk>/homeworks/', views.coach.team_homeworks, name='coach_team_homeworks'),
    path('coach/team/<int:pk>/homeworks/create/', views.coach.team_homeworks_create, name='coach_team_homeworks_create'),
    path('coach/team/<int:pk>/homeworks/<int:hpk>/delete/', views.coach.team_homeworks_delete, name='coach_team_homeworks_delete'),
    path('coach/team/<int:pk>/homeworks/<int:hpk>/edit/', views.coach.team_homeworks_edit, name='coach_team_homeworks_edit'),
    path('coach/team/<int:pk>/homeworks/<int:hpk>/work/', views.coach.team_homeworks_work, name='coach_team_homeworks_work'),
    path('coach/team/<int:pk>/rewards/', views.coach.team_rewards, name='coach_team_rewards'),
    path('coach/team/<int:pk>/rewards/add/', views.coach.team_rewards_add, name='coach_team_rewards_add'),
    path('coach/team/<int:pk>/rewards/<int:rpk>/delete/<int:upk>/', views.coach.team_rewards_delete, name='coach_team_rewards_delete'),
    path('coach/team/<int:pk>/indicators/', views.coach.team_indicators, name='coach_team_indicators'),
    path('coach/team/<int:pk>/indicators/<int:ipk>/add/', views.coach.team_indicators_add, name='coach_team_indicators_add'),
    path('coach/team/<int:pk>/indicators-staic/', views.coach.team_indicators_static, name='coach_team_indicators_static'),

]
